CREATE INDEX IF NOT EXISTS c0 ON osm2 (c0);
CREATE INDEX IF NOT EXISTS c1 ON osm2 (c1);
CREATE INDEX IF NOT EXISTS c2 ON osm2 (c2);
CREATE INDEX IF NOT EXISTS d0 ON osm2 (d0);
CREATE INDEX IF NOT EXISTS d1 ON osm2 (d1);
CREATE INDEX IF NOT EXISTS all_index ON osm2(c0,c1,c2,d0,d1);
